services:
  - type: web
    name: usinas
    env: python
    plan: standard

    buildCommand: |
      bash build.sh && pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: RENDER
        value: "true"

    aptPackages:
      - tesseract-ocr
      - chromium
      - wget
      - unzip
      - curl
      - jq