"""Remove intervalo_leitura from FaturaMensal

Revision ID: 04d9c26a591c
Revises: b99ab87647e4
Create Date: 2025-05-23 10:53:48.168659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d9c26a591c'
down_revision = 'b99ab87647e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faturas_mensais', schema=None) as batch_op:
        batch_op.alter_column('tarifa_neoenergia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=False)
        batch_op.drop_column('intervalo_leitura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faturas_mensais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_leitura', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('tarifa_neoenergia',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
