"""Descrição da mudança

Revision ID: 0bc3e7e18c98
Revises: 
Create Date: 2025-05-22 16:45:48.492403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc3e7e18c98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('codigo_unidade', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('usina_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usinas', ['usina_id'], ['id'])

    with op.batch_alter_table('geracoes', schema=None) as batch_op:
        batch_op.alter_column('usina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('energia_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_foreign_key(None, 'usinas', ['usina_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geracoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('energia_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('usina_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usina_id')
        batch_op.drop_column('codigo_unidade')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
