"""Adiciona campo potencia_kw em Usina

Revision ID: 4eda5244152d
Revises: e855424a0191
Create Date: 2025-05-29 15:53:39.618087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eda5244152d'
down_revision = 'e855424a0191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potencia_kw', sa.Float(), nullable=True))
        batch_op.drop_column('previsao_mensal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previsao_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('potencia_kw')

    # ### end Alembic commands ###
