"""Adiciona campo codigo_rateio ao modelo Rateio

Revision ID: 4ef1848d4e49
Revises: 7629522e770e
Create Date: 2025-06-10 15:27:26.980764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef1848d4e49'
down_revision = '7629522e770e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rateios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_rateio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rateios', schema=None) as batch_op:
        batch_op.drop_column('codigo_rateio')

    # ### end Alembic commands ###
