"""Criar tabela geracoes_inversores

Revision ID: 563935e845d1
Revises: f0e9fc57c3cb
Create Date: 2025-06-05 17:51:47.271493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563935e845d1'
down_revision = 'f0e9fc57c3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geracoes_inversores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usina_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usinas', ['usina_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geracoes_inversores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usina_id')

    # ### end Alembic commands ###
