"""Adiciona campo logo_url à tabela usinas

Revision ID: 7629522e770e
Revises: 563935e845d1
Create Date: 2025-06-10 14:37:49.893114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7629522e770e'
down_revision = '563935e845d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usinas', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
