"""Adiciona campos email e telefone em Cliente

Revision ID: a2a347cc0164
Revises: 4eda5244152d
Create Date: 2025-06-03 14:40:04.046614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a347cc0164'
down_revision = '4eda5244152d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
