"""Adiciona campos inicio_leitura e fim_leitura

Revision ID: b99ab87647e4
Revises: 0bc3e7e18c98
Create Date: 2025-05-23 09:56:50.051404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99ab87647e4'
down_revision = '0bc3e7e18c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faturas_mensais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inicio_leitura', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fim_leitura', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faturas_mensais', schema=None) as batch_op:
        batch_op.drop_column('fim_leitura')
        batch_op.drop_column('inicio_leitura')

    # ### end Alembic commands ###
