"""Adiciona campo pode_acessar_financeiro ao modelo Usuario

Revision ID: c6567dadf6e1
Revises: 1b11bd61c12b
Create Date: 2025-06-12 11:09:28.084827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6567dadf6e1'
down_revision = '1b11bd61c12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pode_acessar_financeiro', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('pode_acessar_financeiro')

    # ### end Alembic commands ###
