"""Adiciona tabela PrevisaoMensal

Revision ID: e855424a0191
Revises: 
Create Date: 2025-05-29 14:47:16.335811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e855424a0191'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previsoes_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usina_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('previsao_kwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usina_id'], ['usinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previsoes_mensais')
    # ### end Alembic commands ###
