"""Cria tabela Inversor e remove inverter_sn de Usina

Revision ID: f0e9fc57c3cb
Revises: a2a347cc0164
Create Date: 2025-06-04 16:33:19.610930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e9fc57c3cb'
down_revision = 'a2a347cc0164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inversores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inverter_sn', sa.String(), nullable=False),
    sa.Column('usina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usina_id'], ['usinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inverter_sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inversores')
    # ### end Alembic commands ###
